version: "2.2"
services:
  eventstore:
    restart: always
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
